<?php

namespace OC\QuizgenBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QCMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QCMRepository extends EntityRepository
{
}
