<?php

namespace OC\QuizlaunchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointQuestionRepository extends EntityRepository

{


      public function getPointQuestionByGamepin($gamepin) {
	      
		      $pointsq = $this->createQueryBuilder('s')
			      ->where('s.gamepin=:gamepin')
			      ->setParameter('gamepin', $gamepin)
			     
		      ;

		      return $pointsq
			->getQuery()
			->getResult()
		      ;
	      
	      }
	      
}
