<?php

namespace App\Repository;

use App\Entity\Quiz;
use App\Entity\Access;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;

/**
 * QuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Quiz::class);
    }
    public function findPublicQuizes() {
         $qb = $this->createQueryBuilder('q');
        // q.access refers to the "access" value
        $qb->select('q')
        ->join('q.access', 'a')
        // selects all the public access data to avoid the query
        ->where('a.name = ?1')
        ->setParameter(1, 'public');
//        ->from('App\Entity\Quiz', 'q')
//        ->from('App\Entity\Access', 'a')
;
 //       return array();
        return $qb
        ->getQuery()
        ->getResult();
 
 
    }
}
