 <?php
 $title = 'Supprimer un album';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Êtes vous sur de vouloir supprimer le questionnaire
     '<?php echo $this->escapeHtml($album->title); ?>' créé par 
     '<?php echo $this->escapeHtml($album->artist); ?>'?
 </p>
 <?php
 $url = $this->url('album', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $album->id; ?>" />
     <input type="submit" name="del" value="Oui" />
     <input type="submit" name="del" value="Non" />
 </div>
 </form>