<?php
namespace App\Repository;
use Doctrine\ORM\EntityRepository;
// use Doctrine\ORM\QueryBuilder;

/**
 * ReponseQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseQuestionRepository extends EntityRepository
{
	public function getReponsesUtilisateur($gamepin,$user,$hdebut,$hfin)
	{
	 
		$qb = $this->createQueryBuilder('r')
			->where('r.gamepin = :gamepin')
				->setParameter('gamepin', $gamepin)
			->andWhere('r.user = :user')
				->setParameter('user', $user)
			->andWhere('r.time < :hfin')
				->setParameter('hfin', $hfin)
			->andWhere('r.time > :hdebut')
				->setParameter('hdebut', $hdebut)
		;
		
		return $qb
		  ->getQuery()
		  ->getResult()
		;
	
	}
	
	public function getByGamepin($gamepin) {
	
		$qb = $this->createQueryBuilder('r')
			->where('r.gamepin = :gamepin')
				->setParameter('gamepin', $gamepin)
		;
		
		return $qb
		  ->getQuery()
		  ->getResult()
		;
	
	}
	
	
	public function getReponseQuestionTimer($gamepin, $question) {
	
		$qb = $this->createQueryBuilder('rq')
			->join('rq.timer', 't')
			->addselect('t')
			->where('rq.gamepin = :gamepin')
				->setParameter('gamepin', $gamepin)
			->andWhere('t.question = :question')
				->setParameter('question', $question)
		;
		
		return $qb
		  ->getQuery()
		  ->getResult()
		;
	
	}
}