<?php

namespace OC\QuizdisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReponseQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseQuestionRepository extends EntityRepository
{
}
